In [1]:
import numpy as np
import pandas as pd

number_of_points = 100
# create three normal population samples with different parameters
x1 = np.random.normal(loc=5.0, size=number_of_points*2) * 100
y1 = np.random.normal(loc=10.0, size=number_of_points*2) * 10

x2 = np.random.normal(loc=5.0, size=number_of_points*4) * 50
y2 = np.random.normal(loc=5.0, size=number_of_points*4) * 10

x3 = np.random.normal(loc=55.0, size=number_of_points) * 10
y3 = np.random.normal(loc=4.0, size=number_of_points) * 10

x = np.concatenate((x1, x2, x3))
y = np.concatenate((y1, y2, y3))

In [9]:
np.vstack([x,y]).shape

(2, 700)

In [12]:
data = pd.DataFrame(np.vstack([x,y]).T, columns=['x', 'y'])

In [13]:
data

              x           y
0    393.471195   93.238243
1    481.264913  109.069432
2    553.395551   90.882964
3    434.773184   99.115562
4    391.892453  103.310688
..          ...         ...
695  542.808863   47.332954
696  542.803865   36.353290
697  565.252033   40.367250
698  566.635925   44.325318
699  557.295152   38.749311

[700 rows x 2 columns]

In [15]:
data.x

0      393.471195
1      481.264913
2      553.395551
3      434.773184
4      391.892453
          ...
695    542.808863
696    542.803865
697    565.252033
698    566.635925
699    557.295152
Name: x, Length: 700, dtype: float64

In [16]:
x

array([393.47119505, 481.26491323, 553.39555107, 434.77318442,
       391.89245261, 534.77781161, 524.94759964, 585.17362123,
       479.77039733, 366.49884631, 396.8126617 , 517.95641716,
       444.45760315, 509.2037797 , 432.77893852, 572.70674068,
       498.52714796, 401.80274366, 497.77580222, 558.73411301,
       553.86044157, 305.80784282, 359.98126776, 400.50730666,
       659.53038891, 491.05058668, 452.20378747, 513.03041187,
       386.86702591, 645.70714864, 461.33516822, 557.52173811,
       474.39993991, 729.79070977, 441.44384426, 476.35099029,
       520.93619464, 389.01646806, 528.11521368, 505.30258565,
       253.51502468, 474.76993344, 531.26009408, 377.75370639,
       499.66175186, 409.9296485 , 554.79927367, 557.9513925 ,
       549.44728133, 583.92712291, 473.21136742, 459.53406395,
       554.64014293, 414.45167825, 445.9857853 , 449.53927954,
       476.87355343, 513.75223907, 353.73482521, 412.97216254,
       638.38249237, 414.60433338, 250.9534185 , 515.6392572 ,
       447.71033592, 469.80353689, 292.4251546 , 349.23673907,
       566.49949911, 695.78242094, 723.77874874, 415.45835634,
       266.56713768, 484.76084791, 590.74378125, 504.81424706,
       593.79060167, 418.10512214, 412.0136643 , 353.88937852,
       438.5381558 , 368.01046431, 591.81871767, 587.97167752,
       467.36315007, 640.18091403, 480.23506966, 550.16178767,
       699.82787003, 545.74719996, 407.20715528, 484.60496277,
       494.9476439 , 435.51892828, 459.09049414, 637.10935783,
       587.78273416, 450.97238356, 513.90132364, 681.89636695,
       398.61945594, 454.01324787, 557.68458851, 533.61175229,
       476.53161207, 553.98512197, 512.07827433, 491.43489917,
       324.70235808, 402.13566788, 504.28342159, 613.82568326,
       546.4637583 , 423.41044308, 416.7677121 , 471.32918528,
       533.03650978, 507.60752773, 422.86401866, 694.13463036,
       206.39895321, 382.36441622, 434.98789187, 472.96360559,
       546.52016625, 465.09887768, 571.32426472, 487.5356459 ,
       497.61445411, 419.76297411, 489.98880605, 476.38986753,
       465.54224773, 726.12931449, 477.26342244, 653.37957695,
       460.42990841, 497.82331156, 300.83905947, 508.07304459,
       748.77401788, 533.63523912, 621.16941881, 294.59045573,
       447.94511515, 410.05168239, 394.53566703, 611.27823723,
       672.58973048, 686.77324062, 392.98445355, 559.27338504,
       445.44817483, 543.49126465, 580.99416409, 596.0871563 ,
       565.03075624, 609.70227334, 527.38104762, 589.27602887,
       576.91771335, 613.3805174 , 562.08632627, 587.25506323,
       374.60150785, 497.36230419, 266.8297641 , 355.14469104,
       581.6311936 , 516.17499469, 492.13601898, 505.60132417,
       491.63597179, 709.264601  , 300.8738255 , 487.16069076,
       545.79200926, 511.5042507 , 554.82674574, 465.46546515,
       678.66065253, 547.9222903 , 638.87479482, 407.15387871,
       572.13013402, 460.26386358, 685.23029302, 548.65924212,
       472.29316494, 471.33813746, 441.40120785, 641.26122797,
       528.07653297, 464.20362427, 606.96263903, 420.11311537,
       468.89524485, 646.23399155, 394.51613052, 420.37384811,
       298.09543333, 207.85048804, 307.86666894, 325.50797148,
       293.19314302, 332.72832606, 173.89117503, 286.99810146,
       213.57460726, 217.17984631, 242.18388786, 313.34961844,
       195.64946998, 161.35770517, 231.92275151, 177.87426267,
       248.20235422, 243.19446307, 239.88287607, 267.31073525,
       233.74000104, 327.85157868, 322.1483209 , 171.90328693,
       234.7189709 , 201.05608822, 200.83784211, 195.02704566,
       300.12261826, 206.26691188, 291.94007844, 285.54038377,
       193.42933415, 254.12049723, 222.0783307 , 296.88061179,
       303.52751536, 224.82952987, 209.51145867, 223.31428489,
       199.86600918, 299.356477  , 219.61836103, 254.11798517,
       199.8646125 , 238.49160273, 325.88163861, 325.46214072,
       307.25585757, 341.39688569, 189.31912487, 161.20418599,
       221.29754172, 202.30873769, 302.14083416, 249.457666  ,
       204.88817624, 246.40160542, 288.84282286, 328.48343763,
       251.61517122, 206.18157145, 248.69091621, 199.20232623,
       203.56981751, 257.23538282, 166.77683788, 260.87403086,
       293.63035844, 264.17069538, 216.96972966, 246.9603149 ,
       282.17646964, 138.73969418, 280.19614328, 248.13577133,
       260.89836229, 195.14591084, 306.04827167, 215.1578198 ,
       145.86483895, 206.72448178, 208.46781162, 155.57645312,
       196.86164607, 265.70184565, 202.30696539, 276.26981095,
       196.26891931, 193.36313257, 331.35500605, 284.67441964,
       190.04682065, 274.54051979, 377.64376755, 232.69423008,
       186.35584226, 264.46805442, 159.50037189, 263.79494146,
       218.69123608, 220.45333148, 202.35840537, 213.62636337,
       257.58740728, 260.76136573, 290.65847221, 225.92576174,
       369.88652786, 216.00975297, 339.24055739, 277.51176256,
       307.93284672, 266.24884502, 350.4380901 , 224.86892529,
       222.23334309, 231.66164519, 318.60071482, 299.68333848,
       184.77444301, 291.72601643, 262.83017176, 240.7174786 ,
       227.72672404, 283.58399571, 278.45869141, 228.16797367,
       245.69586353, 250.51992672, 314.44909273, 234.3492025 ,
       307.85177246, 266.52127961, 240.19663443, 237.31795936,
       304.92874802, 267.88720503, 188.96513861, 214.49244157,
       189.38852716, 201.52490651, 204.32726553, 180.36982375,
       194.79995013, 238.82652464, 294.24336428, 354.28064334,
       234.64409842, 302.65332935, 273.15485349, 151.17034797,
       359.67718319, 235.74314282, 186.17914163, 231.8634361 ,
       124.52630314, 325.64299695, 237.60507325, 339.54009846,
       290.68832005, 206.0002208 , 227.34941737, 300.66683481,
       231.51091676, 271.46967835, 203.85750512, 270.85875963,
       274.5351519 , 327.29339619, 200.60394735, 292.67979896,
       324.81615035, 310.27817596, 233.7893984 , 132.36930019,
       309.1848162 , 268.26954105, 277.12309564, 212.60679057,
       299.49276758, 223.55026804, 235.57076936, 270.99363086,
       246.67333985, 273.94473055, 320.05358598, 303.00905028,
       232.43874893, 226.04748245, 308.15784437, 252.27402254,
       348.03451227, 156.65793887, 288.32815264, 245.97406008,
       257.73571081, 198.37011135, 161.33777546, 243.86183487,
       353.56104037, 270.83983024, 247.85828848, 301.41533349,
       157.96371225, 214.80410275, 265.13916926, 312.30997952,
       232.7065127 , 348.45181768, 299.52482339, 238.52209739,
       257.22571171, 336.85497855, 280.13178525, 310.19073135,
       114.98164331, 331.62516606, 274.54629063, 308.71892836,
       264.61667367, 200.87095298, 192.85183939, 261.17076671,
       250.58587583, 206.22489515, 215.76897351, 295.9245678 ,
       141.93508141, 233.64698434, 177.92097114, 175.12518042,
       233.1335151 , 243.12225291, 241.42992427, 224.50096666,
       188.32544428, 203.58304886, 217.33542134, 275.90288043,
       305.36061339, 191.76840441, 219.48244994, 304.07843   ,
       245.56062022, 241.23626705, 244.51012378, 246.28954016,
       257.52271134, 263.20595396, 282.69870355, 290.69340663,
       190.00498531, 303.66840176, 252.39339119, 202.16298903,
       293.5052477 , 262.32116516, 178.54772525, 226.20701847,
       329.3325319 , 335.45733541, 327.06161583, 306.91006841,
       237.74389858, 240.41059428, 219.02186363, 289.95406603,
       302.45169858, 302.52374708, 300.33195121, 237.48612707,
       313.21282713, 239.66833423, 242.08486745, 174.57250043,
       272.6788223 , 276.36876001, 263.01221131, 226.22179932,
       174.46582432, 255.45489866, 210.79376837, 276.83893355,
       284.19103328, 257.87796352, 187.61724117, 277.22528911,
       345.43771675, 157.98968983, 278.77134074, 312.19431008,
       267.35004332, 402.20289658, 308.92879729, 321.82142461,
       223.50755618, 247.22029058, 292.47980828, 246.20872529,
       227.50915311, 158.92597367, 357.39112226, 280.06056877,
       146.28859136, 277.34061581, 308.73609743, 280.26530776,
       248.74120246, 199.28805604, 264.0893187 , 275.90102895,
       203.9859019 , 219.29512337, 184.88837045, 184.66810695,
       305.55292268, 214.0112763 , 309.51069762, 276.04533329,
       233.98949765, 297.65722911, 236.10426644, 154.56654878,
       192.70129193, 198.5344709 , 310.71189527, 198.29556809,
       228.25654298, 213.9890798 , 272.51715627, 215.31748608,
       289.31548638, 148.00144846, 245.38883767, 164.83071096,
       267.58596527, 264.83517419, 303.11877385, 256.7092344 ,
       248.24183449, 238.13029782, 163.38431411, 221.03862207,
       224.29955028, 178.20413416, 216.50066723, 178.80266019,
       170.25093145, 211.97392756, 358.25198725, 226.21594676,
       230.60118728, 274.49003818, 273.29207069, 258.05913251,
       320.30069863, 299.96317428, 247.99783134, 188.92203703,
       325.34896787, 187.55171104, 223.18864472, 297.90492792,
       254.34382914, 272.0087996 , 205.45979084, 343.01571015,
       229.37044696, 326.36787028, 231.84215083, 210.65203757,
       277.92695071, 308.13277286, 254.55581152, 313.59840292,
       289.72342746, 270.32119341, 244.35608612, 268.67090977,
       233.09469837, 254.49539406, 289.44723308, 210.40839882,
       253.93952278, 349.23213143, 202.2168102 , 245.50315194,
       297.22976424, 235.15257358, 188.60598897, 253.06428513,
       223.22377543, 231.56310633, 282.42161228, 212.14828475,
       199.29350376, 195.61419718, 274.99027361, 296.62235581,
       555.20583271, 538.67661204, 555.49939535, 549.06191184,
       550.14260791, 549.2763082 , 555.06623081, 555.52814037,
       564.33173949, 549.92895157, 542.1061265 , 537.79387271,
       561.03059861, 557.40118831, 554.65454968, 571.09757361,
       545.1667006 , 557.6519508 , 548.08658843, 541.56883419,
       550.92442959, 562.72150151, 551.68618716, 549.94866201,
       528.01423789, 547.02664117, 562.05426438, 554.75608881,
       567.93974288, 552.67656403, 559.51801077, 545.78032442,
       551.09985114, 532.65315116, 543.89635454, 543.85071643,
       548.26758556, 550.55880631, 546.76954489, 564.87918936,
       555.84925262, 546.73805889, 561.86400942, 566.82087787,
       577.43077882, 565.23621385, 543.30513252, 548.98168069,
       544.84498361, 546.23461402, 548.45915639, 557.93663733,
       553.97418777, 544.48509255, 573.88806766, 532.36049741,
       559.84887502, 562.98678697, 543.38686008, 557.41859712,
       536.28330369, 544.49782655, 563.40384828, 544.31165514,
       546.53718723, 557.73324508, 555.60339632, 553.36068279,
       558.37954816, 547.6199013 , 545.58827326, 556.87624982,
       572.04678724, 543.25289972, 533.9722365 , 561.47856064,
       548.79281417, 551.50346058, 544.44406425, 551.27540623,
       521.27197741, 550.46110619, 545.70922868, 568.60307123,
       566.47203698, 556.08149381, 545.40375553, 549.18239022,
       537.38136354, 556.07493693, 557.01255312, 527.67960943,
       541.04705002, 561.27586994, 561.73081183, 542.80886313,
       542.80386549, 565.25203293, 566.63592457, 557.29515241])

In [17]:
x.shape

(700,)

In [18]:
pd.DataFrame(x, columns=['x'])

              x
0    393.471195
1    481.264913
2    553.395551
3    434.773184
4    391.892453
..          ...
695  542.808863
696  542.803865
697  565.252033
698  566.635925
699  557.295152

[700 rows x 1 columns]